//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWiLi.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ItemActivities = new HashSet<ItemActivity>();
        }
    
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int ListId { get; set; }
        public int CategoryId { get; set; }
        public string DisplayName { get; set; }
        public int Quantity { get; set; }
        public string LocationDisplayName { get; set; }
        public string LocationUri { get; set; }
        public string Price { get; set; }
        public string Metadata { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual List List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemActivity> ItemActivities { get; set; }
        public virtual Category Category { get; set; }
    }
}
