//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWiLi.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime Attempt { get; set; }
        public string IP { get; set; }
        public bool Success { get; set; }
    }
}
